### PR TITLE
Update user to support multiple jurisdictions

### PR DESCRIPTION
**Pull request by LaurelOlson**
## Description

Update user to support multiple jurisdictions

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📦 Chore (Release)
- [ ] ✅ Test

## Related Tickets & Documents

[BPHH-1267](https://hous-bssb.atlassian.net/browse/BPHH-1267)

## Steps to QA

Verify general happy paths still work as expected (especially for reviewers/review managers)

## UI Accessibility Checklist

_Note the following checklist is not an exhaustive list. Check
the [WebAIM checklist](https://webaim.org/standards/wcag/checklist) for
a user-friendly checklist with more details. Aim to meet at least *AA* conformance level where applicable. Check
the [WCAG guidelines](https://webaim.org/standards/wcag/checklist) for the full guidelines._

- [ ] Markup uses semantic HTML?
- [ ] Additional context added through `aria-roles` and `aria-labels`?
- [ ] Checked
      with [Wave Browser Extension](https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)
      for accessibility errors?
- [ ] Usable with a keyboard and navigable in a logical order?
- [ ] Usable using a screen reader (e.g. Voiceover for Mac) with enough context for the user?

## General Checklist

- [ ] ✅ Provide tests for your changes where relevant
- [x] 📝 Use descriptive commit messages
- [ ] 📗 Update any related documentation and include any relevant screenshots
- [ ] 📱 For UI-related tasks, ensure responsive design is implemented across multiple screen size
- [x] 🗂️ Move your relevant story/task to the _Ready for Code Review_ state

## [optional] Are there any post-deployment tasks we need to perform?

n/a

### CODE REVIEW

**Comment by bkmaibach** [comment]
in our enums.ts file we have:

`
export enum EUserRoles {
  submitter = "submitter",
  reviewManager = "review_manager",
  reviewer = "reviewer",
  superAdmin = "super_admin",
}`

should we consider adding the new role? perhaps user helper methods? Does the new role have a new home screen?

**Comment by bkmaibach** [comment]
I'm noticing that for some reason, the wrong role is being assigned to the review_manager after signup...

image

**Comment by bkmaibach** [comment]
I'm noticing that for some reason the wrong role is being assigned to the review_manager after I log in with bceid:

image

**Comment by bkmaibach** [comment]
for some reason the role of "submitter" is being assigned to the review_manager bceid

**Comment by taw27** [comment]
@LaurelOlson I rebased this and the integration branches so you will need to pull again

**Review by taw27 — APPROVED** [review]

**Pull request merged**
